apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-core-configmap
  namespace: default
data:
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_mode: "CORE"
  NEO4J_AUTH: "neo4j/s00pers3cret"
  NEO4J_dbms_security_auth__enabled: "true"
  NEO4J_dbms_backup_enabled: "true"
  NEO4J_dbms_backup_listen__address: ":6362"
  NEO4J_dbms_memory_heap_initial__size: "1G"
  NEO4J_dbms_memory_heap_max__size: "1G"
  NEO4J_dbms_memory_pagecache_size: "2G"
  NEO4J_dbms_tx__state_memory__allocation: "ON_HEAP"
  NEO4J_dbms_default__listen__address: "0.0.0.0"
  NEO4J_dbms_connector_bolt_enabled: "true"
  NEO4J_dbms_connector_bolt_tls__level: "DISABLED"
  NEO4J_dbms_connector_bolt_advertised__address: ":7687"
  NEO4J_dbms_connector_bolt_listen__address: ":7687"
  NEO4J_dbms_connector_http_enabled: "true"
  NEO4J_dbms_connector_http_advertised__address: ":7474"
  NEO4J_dbms_connector_http_listen__address: ":7474"
  NEO4J_dbms_connector_https_enabled: "false"
  NEO4J_dbms_connector_https_advertised__address: ":7473"
  NEO4J_dbms_connector_https_listen__address: ":7473"
  NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: "3"
  NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime: "2"
  NEO4J_causal__clustering_discovery__advertised__address: ":5000"
  NEO4J_causal__clustering_transaction__advertised__address: ":6000"
  NEO4J_causal__clustering_raft__advertised__address: ":7000"
  NEO4J_causal__clustering_discovery__listen__address: ":5000"
  NEO4J_causal__clustering_transaction__listen__address: ":6000"
  NEO4J_causal__clustering_raft__listen__address: ":7000"
  NEO4J_causal__clustering_initial__discovery__members: "neo4j-core1.neo4jdb-cluster-service.default.svc.cluster.local:5000,neo4j-core2.neo4jdb-cluster-service.default.svc.cluster.local:5000,neo4j-core3.neo4jdb-cluster-service.default.svc.cluster.local:5000"
